### Set Up by: Christian Garcia (TACC)
### Release-* methodology originally authored by Nathan Freeman (TACC) here:
### https://github.com/tapis-project/tapis-workflows/blob/prod/.github/workflows/ci.yml#L59
# Description. This Github action runs when there are new commits to dev, stage, master, or release-*.
# The action logs into Docker with the Github action environment secrets `DOCKERHUB_USERNAME`
# and `DOCKERHUB_TOKEN`.
# The action pulls the repo and builds the tapis/ci-catalog image and uses branch name as the
# docker tag. In instance of `release-1.2.0`, sed will delete `release-`, leaving `1.2.0`.
# If branch = master, tag becomes `latest` so latest is built.
#
### Variables
#   vars.DOCKERHUB_USERNAME: Docker username
#   secrets.DOCKERHUB_TOKEN: Docker token
#   secrets.TAPIS_ICICLE_PROD_TOKEN: token for Tapis user
#   vars.POD_ID: components
#   vars.DEV_POD_ID: componentsdev

name: Build & Push & Deploy
on:
  push:
    branches: [ dev, staging, master, release-* ]
  workflow_dispatch:

jobs:
  build-and-push-images:
    runs-on: ubuntu-latest
    steps:
      - name: Get tag name from branch. SED removes `release-`, replaces `master` with `latest`.
        id: get_tag_name
        shell: bash
        run: echo "tag_name=$(echo ${GITHUB_REF#refs/heads/} | sed 's/master/latest/g' | sed 's/release-//g')" >> $GITHUB_OUTPUT
        
      - name: Checkout repo
        uses: actions/checkout@v3
        
      - name: Grab config file
        shell: bash
        env: 
          CONFIG_FILE: ${{ contains('refs/heads/master', github.ref) && secrets.OAUTH_CONFIG_PROD || secrets.OAUTH_CONFIG_DEV }}
        run: echo ${CONFIG_FILE}

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        
      - name: Build & push tagged Docker backend image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: tapis/ci-catalog:${{ steps.get_tag_name.outputs.tag_name }}

  deploy-images-dev:
    runs-on: ubuntu-latest
    needs: [build-and-push-images]
    if:
      contains('refs/heads/dev', github.ref)
    steps:
    - name: Restart dev pod
      uses: fjogeleit/http-request-action@v1
      with:
        url: 'https://icicle.tapis.io/v3/pods/${{ vars.DEV_POD_ID }}/restart'
        method: 'GET'
        customHeaders: '{"Content-Type": "application/json", "X-Tapis-Token": "${{ secrets.TAPIS_ICICLE_PROD_TOKEN }}"}'

  deploy-images:
    runs-on: ubuntu-latest
    needs: [build-and-push-images]
    if:
      contains('refs/heads/master', github.ref)
    steps:
    - name: Restart pod
      uses: fjogeleit/http-request-action@v1
      with:
        url: 'https://icicle.tapis.io/v3/pods/${{ vars.POD_ID }}/restart'
        method: 'GET'
        customHeaders: '{"Content-Type": "application/json", "X-Tapis-Token": "${{ secrets.TAPIS_ICICLE_PROD_TOKEN }}"}'
